global:
  scrape_interval: 5s   # how often to collect metrics
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask:5000']
      - targets: ['host.docker.internal:5000']
