services:
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      - GRAPHITE_TIME_ZONE=UTC
    restart: unless-stopped
